baseURL = "https://QQMKCR.github.io/"
languageCode = "vi-vn"  # NgÃ´n ngá»¯ tiáº¿ng Viá»‡t
title = "Blog cá»§a [TÃªn báº¡n]"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Wuag - QuÃ¡ch Quang Minh "
  description = "Sinh viÃªn CÃ´ng nghá»‡ ThÃ´ng tin Ä‘am mÃª lÄ©nh vá»±c PhÃ¢n tÃ­ch dá»¯ liá»‡u, cÃ³ ká»¹ nÄƒng sá»­ dá»¥ng Python, SQL, Excel, Power BI Ä‘á»ƒ xá»­ lÃ½ vÃ  trá»±c quan hÃ³a dá»¯ liá»‡u."
  github = "QQMKCR"  # TÃªn tÃ i khoáº£n GitHub
  email = "nguyenminhkcr1@gmail.com"  # Email cá»§a báº¡n
  location = "Viá»‡t Nam"  # Vá»‹ trÃ­ cá»§a báº¡n
  favicon = "/images/favicon.png"  # ÄÆ°á»ng dáº«n Ä‘áº¿n favicon
  avatar = "/images/avatar.png"  # ÄÆ°á»ng dáº«n Ä‘áº¿n áº£nh Ä‘áº¡i diá»‡n
  userStatusEmoji = "ğŸ˜€"  # Emoji thá»ƒ hiá»‡n tráº¡ng thÃ¡i
  rss = true
  lastmod = true
  enableSearch = true  # TÃ¬m kiáº¿m cá»¥c bá»™ (tÃ¹y chá»n)

  # LiÃªn káº¿t máº¡ng xÃ£ há»™i hoáº·c website
  #[[params.links]]
  #  title = "LinkedIn"
  #  href = "https://linkedin.com/in/yourprofile"
  #  icon = "/images/linkedin-icon.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false