baseURL = "https://QQMKCR.github.io/"
languageCode = "vi-vn"  # NgÃ´n ngá»¯ tiáº¿ng Viá»‡t
title = "Blog cá»§a Wuag"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "QuÃ¡ch Quang Minh"
  description = "Sinh viÃªn nÄƒm cuá»‘i - Hiá»‡n Ä‘ang táº­p trung xÃ¢y dá»±ng ká»¹ nÄƒng phÃ¢n tÃ­ch dá»¯ liá»‡u thÃ´ng qua cÃ¡c dá»± Ã¡n thá»±c táº¿ vÃ  cÃ´ng cá»¥ nhÆ° Python (Pandas, NumPy), SQL, Power BI vÃ  Excel. Má»¥c tiÃªu trá»Ÿ thÃ nh Data Analyst chuyÃªn nghiá»‡p, cÃ³ kháº£ nÄƒng chuyá»ƒn Ä‘á»•i dá»¯ liá»‡u thÃ´ thÃ nh thÃ´ng tin chiáº¿n lÆ°á»£c há»— trá»£ ra quyáº¿t Ä‘á»‹nh.."
  email = "nguyenminhkcr1@gmail.com"  # Email cá»§a báº¡n
  location = "Viá»‡t Nam"  # Vá»‹ trÃ­ cá»§a báº¡n
  favicon = "/images/favicon.png"  # ÄÆ°á»ng dáº«n Ä‘áº¿n favicon
  avatar = "/images/avatar.png"  # ÄÆ°á»ng dáº«n Ä‘áº¿n áº£nh Ä‘áº¡i diá»‡n
  userStatusEmoji = "ğŸ˜€"  # Emoji thá»ƒ hiá»‡n tráº¡ng thÃ¡i
  rss = true
  lastmod = true
  enableSearch = true  # TÃ¬m kiáº¿m cá»¥c bá»™ (tÃ¹y chá»n)

  showSkills = true
  skillsTitle = "Ká»¹ nÄƒng"

  [[params.skills]]
    name = "Python"
    level = 65
    icon = "fab fa-python"

  [[params.skills]]
    name = "SQL"
    level = 85
    icon = "fas fa-database"

  [[params.skills]]
    name = "Power BI"
    level = 45
    icon = "fas fa-chart-bar"

  [[params.skills]]
    name = "Excel"
    level = 60
    icon = "fas fa-table"

  [[params.skills]]
    name = "Git & GitHub"
    level = 70
    icon = "fab fa-github"

  # LiÃªn káº¿t máº¡ng xÃ£ há»™i hoáº·c website
  #[[params.links]]
  #  title = "LinkedIn"
  #  href = "https://linkedin.com/in/yourprofile"
  #  icon = "/images/linkedin-icon.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false


